/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidndkapp1_Data */

#ifndef _Included_com_example_androidndkapp1_Data
#define _Included_com_example_androidndkapp1_Data
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidndkapp1_Data
 * Method:    stringtojni
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_androidndkapp1_Data_stringtojni
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_androidndkapp1_Data
 * Method:    stringfromjni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androidndkapp1_Data_stringfromjni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
